# Generated by Django 3.2.4 on 2022-04-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactslist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
